country_full_name = {
    "IN": "India",
    "PK": "Pakistan",
    "CN": "China",
    "NP": "Nepal",
    "BD": "Bangladesh",
    "US": "United States",
    "CA": "Canada",
    "MX": "Mexico",
    "FR": "France",
    "DE": "Germany",
    "IT": "Italy",
    "ES": "Spain",
    "PL": "Poland",
    "NZ": "New Zealand",
    "AU": "Australia",
    "SA": "Saudi Arabia",
    "IR": "Iran",
    "ZA": "South Africa",
}

adjacent_countries = {
    "IN": ["Pakistan", "China", "Nepal", "Bhutan", "Bangladesh", "Myanmar"],
    "PK": ["India", "China", "Afghanistan", "Iran"],
    "CN": ["India", "Pakistan", "Nepal", "Bhutan", "Myanmar", "Russia", "Mongolia", "North Korea"],
    "NP": ["India", "China"],
    "BD": ["India", "Myanmar"],
    "US": ["Canada", "Mexico"],
    "CA": ["United States"],
    "MX": ["United States", "Guatemala", "Belize"],
    "FR": ["Belgium", "Germany", "Italy", "Spain", "Switzerland", "Luxembourg", "Monaco"],
    "DE": ["Poland", "Czech Republic", "Austria", "France", "Belgium", "Netherlands", "Luxembourg", "Switzerland", "Denmark"],
    "IT": ["France", "Switzerland", "Austria", "Slovenia"],
    "ES": ["Portugal", "France", "Andorra"],
    "PL": ["Germany", "Czech Republic", "Slovakia", "Ukraine", "Belarus", "Lithuania", "Russia"],
    "NZ": [],
    "AU": [],
    "SA": ["Jordan", "Iraq", "Kuwait", "Qatar", "United Arab Emirates", "Oman", "Yemen"],
    "IR": ["Turkey", "Iraq", "Pakistan", "Afghanistan", "Turkmenistan", "Azerbaijan", "Armenia"],
    "ZA": ["Botswana", "Namibia", "Zimbabwe", "Mozambique", "Eswatini", "Lesotho"],
}
